student-group-view-modal-bugs
ctc-uci/the-literacy-project-frontend pull request #179
Opened 2022-05-13 21:07 UTC by ctc-devops

1. Condense the code in [lines 40-74](https://github.com/ctc-uci/the-literacy-project-frontend/blob/554680203f913598277107cf5df31cd606572f64/src/pages/student-group-view/student-group-view.jsx#L40) of student-group-view.jsx to use just one backend request (I think `/student-groups/${studentGroupId}` should give you all the information you need including the site info).
2. Address [Bug #15](https://docs.google.com/document/d/1b_9mVzrmdU1dpDv7BXmqoMXjOhU2f-RAY8SYv-BFU80/edit#heading=h.lmeoi9lqako9)
closes #173

2022-05-13 23:55 UTC, anikait-rao requested changes
1. The list of possible students that can be added in both the Create and Edit Student Group modals needs to only be students who do not have a student group - their groupId would be `null`.
2. Can we have it so that when they press "Save" the student group page reloads

2022-05-25 20:31 UTC, ctc-devops commented on src/pages/student-group-view/student-group-view.jsx
> +    console.log('request');
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-25 20:31 UTC, ctc-devops commented on src/pages/student-group-view/student-group-view.jsx
> +    console.log(groupUpdated);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-25 20:39 UTC, anikait-rao approved these changes
looks good

2022-05-25 20:39 UTC, merged