update-admin-signup
ctc-uci/the-literacy-project-frontend pull request #186
Opened 2022-05-16 02:45 UTC by ctc-devops

closes #140

2022-05-18 04:16 UTC, ctc-devops commented on src/components/FinishAccount/FinishAccount.jsx
> +  const toggleNewPasswordVisibility = () => {
🚫 **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'toggleNewPasswordVisibility' is assigned a value but never used.

2022-05-18 04:16 UTC, ctc-devops commented on src/components/FinishAccount/FinishAccount.jsx
> +    handleSubmit,
🚫 **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'handleSubmit' is assigned a value but never used.

2022-05-18 04:16 UTC, ctc-devops commented on src/components/FinishAccount/FinishAccount.jsx
> +        <form className={`form-group ${styles['site-form']}`} onSubmit={handleResetPassword}>
🚫 **[eslint]** <[no-undef](https://eslint.org/docs/rules/no-undef)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'handleResetPassword' is not defined.

2022-05-20 05:08 UTC, anikait-rao requested changes
People page errors when merging dev so I can't test account creation flow - might need to merge dev?

2022-05-20 05:08 UTC, anikait-rao commented on src/common/utils.js
> +  'https://docs.google.com/document/d/1MNoU_GbLX8xV2t28pBLt-mbR2XbVwiOENNtLZSSECU0/edit?usp=sharing';
merge dev into your branch and put these in configs.js

2022-05-31 22:18 UTC, anikait-rao approved these changes
looks good

2022-05-31 22:18 UTC, merged