staff-tab
ctc-uci/the-literacy-project-frontend pull request #57
Opened 2022-02-26 00:54 UTC by ctc-devops

Make the staff tab of the people page look like the mid-fi design - update the CSS.

https://www.figma.com/file/O2igPzMS1fZPzjmOxlo6Mc/TLP-Wireframes?node-id=538%3A23322

![image](https://user-images.githubusercontent.com/57849152/155804685-bb2fef66-d47d-4280-b81c-742c59cd1dde.png)

closes #50

2022-03-22 05:48 UTC, ctc-devops commented on src/common/utils.js
> +  console.log('values:', values);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-03-31 22:51 UTC, joshualchan commented
<img width="1403" alt="Screen Shot 2022-03-31 at 3 48 07 PM" src="https://user-images.githubusercontent.com/19737385/161161999-2e9a1836-9944-43c5-a9a0-10018b07b9c3.png">

Finished
- Populated the staff tab tables
- Completed the create and edit modals for both admins, MTs

Unfinished
- Adding sites to MTs
- Filter, sorting the tables
- Input validations for create and edit modals

2022-04-01 00:01 UTC, anikait-rao requested changes
1. Please change the master-teachers.jsx file to be named something like 'master-teachers-table.jsx'. Also change the component name to be "MasterTeacherTableView". This is because there is a separate master teacher dashboard and I don't want that to become confusing.
2. Update the CSS of this staff tab so that it is closer to the figma. The shade of blue used throughout our project is #3288C4 (for the sort tab, filter tab, etc.).
3. Rename the Management data section CSS file to follow .module.css conventions (and make corresponding changes if necessary).

2022-04-02 08:06 UTC, anikait-rao approved these changes
looks good

2022-04-02 08:06 UTC, merged