update-area-management-styling
ctc-uci/the-literacy-project-frontend pull request #67
Opened 2022-03-05 22:20 UTC by ctc-devops

Make the area management look like the mid-fi design - update the CSS.

Also, change the file type from .css to .module.css so that the CSS changes are not global ([Read more about this issue here](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/
))

https://www.figma.com/file/O2igPzMS1fZPzjmOxlo6Mc/TLP-Wireframes?node-id=538%3A23322

![image](https://user-images.githubusercontent.com/57849152/155774025-61295aa5-bdbd-4046-90ef-20aa9d58cd73.png)

closes #49

2022-03-06 01:48 UTC, ctc-devops commented on src/pages/sites/sites.jsx
> +                  console.log('needs functionality');
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-03-31 08:14 UTC, anikait-rao requested changes
Some minor changes:
1. Please update the CSS files to use .module.css as described in [this message](https://ctcuci.slack.com/archives/C02KJ1EGKUG/p1648524217683049)
2. Add a "Filter By" button to the left of the "sort by" button as in the figma.
3. Change the colors for all the buttons to match the shade of blue used in the figma (#3288C4)

2022-04-02 23:59 UTC, allenxluo requested changes
- For the backend logic, can you make it so you don't have to refresh the page to see the new area. Look into reloading a component on update.
- Slight nitpick but can you increase the font size of the **Areas** header

2022-04-04 03:28 UTC, anikait-rao approved these changes
looks good

2022-04-04 03:35 UTC, merged